title: "<質問のタイトルを入れましょう>"
body:
  - type: markdown
    attributes:
      value: |
        詰まる所は皆一緒！このチャンネルで助け合っていきましょう！！
        ## 🙇‍♀️　ラベル(label)を設定しよう
        研修生・受講生同士で、過去に出た質問を見るときの検索の容易性を上げるために、ラベルを設定しましょう！
        右の**label**から自分の質問に内容に合うものを設定しましょう！
        ## 💪 質問を書いていこう
  - type: textarea
    id: problem
    attributes:
      label: 問題（何に困っているか）
      description: "今困っていることを言語化してみましょう！ また、どの教科書の何ページやオリジナルWebサービスのどこで詰まっているなどを記入しましょう！"
      value: " "
    validations:
      required: true
  - type: textarea
    id: try
    attributes:
      label: 自分で挑戦してみたこと・試してみたこと
      description: "どんなコマンドを打ってみた。こんな記事を参考にしてみたなどなんでもOK"
      value: " "
    validations:
      required: true
  - type: textarea
    id: error-photo
    attributes:
      label: エラー画面のスクショ
      description: "エラーが起こっている画面のスクリーンショットを貼ってください！"
      value: " "
    validations:
      required: true
