name: Create Pull Request to Main

on:
  push:
    branches:
      - staging

jobs:
  create_pull_request:
    runs-on: ubuntu-latest
    
    env:
      GH_TOKEN: ${{ secrets.GH_CUSTOM_TOKEN }}

    steps:
      - name: Check for existing Pull Request
        id: check_pr
        run: |
          pr_list=$(gh pr list --base main --head staging --json title,body,number)
          echo "::set-output name=pr_list::$pr_list"

      - name: Create or Update Pull Request
        id: pr
        run: |
          timestamp=$(date +"%Y-%m-%d %T")
          diff=$(echo "${{ steps.check_pr.outputs.pr_list }}" | jq -r '.[0].title, .[0].body')
          if [ -z "$diff" ]; then
            gh pr create --title "RELEASE: $timestamp" --body "$diff"
          else
            pr_number=$(echo "${{ steps.check_pr.outputs.pr_list }}" | jq -r '.[0].number')
            gh pr update $pr_number --title "RELEASE: $timestamp" --body "$diff"
          fi
