name: Create a pull request for release.

on:
  push:
    branches: [ staging ]

jobs:
  create-release-pr:
    runs-on: ubuntu-latest

    env:
      base_branch: main
      GH_TOKEN: ${{ secrets.GH_CUSTOM_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      # リリース用PRが既に存在するかどうかをチェック
      - name: Check if pr exists
        id: check_pr
        run: |
          echo "::set-output name=count::$(gh pr list -base main | wc -l)"

      - name: Fetch base branch
        run: git fetch origin ${base_branch}:${base_branch}

      - name: Run actions using diff_files
        id: get_diff
        run: |
          diff_files=$(git diff --name-only HEAD ${base_branch} -- "${diff_path}" \
            | tr "\n" " ")
          echo "::set-output name=diff_files::${diff_files}"
      
      - name: Get current datetime as env variable
        id: get_datetime
        env:
          TZ: 'Asia/Tokyo'
        run: |
          echo "::set-output name=current_datetime::$('%Y-%m-%d %H:%M:%S')"
          
      # リリース用PRを作成
      - name: Create release pr
        env:
          TZ: 'Asia/Tokyo'
        run: |
          gh pr create -B ${base_branch} -t 'RELEASE:'${{steps.get_datetime.outputs.current_datetime}} -b ${{steps.get_diff.outputs.diff_files}}
          
