name: DiscussionNotification

on:
  discussion:
    types: [created, answered]

jobs:
  discussion:
    runs-on: ubuntu-22.04
    steps:
      - name: Read config.json
        id: config
        uses: jaywcjlove/github-action-read-file@main
        with:
          path: config.json
      - name: Write Config
        run: |
          echo "CONFIG=${{ fromJson(steps.config.outputs.content) }}" >> $GITHUB_ENV
          
      - name: Get Discussion Action
        run: |
          echo "ACTION=${{ github.event.action }}" >> $GITHUB_ENV
          echo "DISCUSSION_URL=${{ github.event.discussion.html_url }}" >> $GITHUB_ENV
          echo "DISCUSSION_TITLE=${{ github.event.discussion.title }}" >> $GITHUB_ENV
          echo "DISCUSSION_BODY=${{ github.event.discussion.body }}" >> $GITHUB_ENV
          echo "DISCUSSION_USER_NAME=${{ github.event.discussion.user.login }}" >> $GITHUB_ENV
      - name: Get Answer Action
        if: env.ACTION == 'answered'
        run: |
          echo "ANSWER_ANSWER_URL=${{ github.event.answer.html_url }}" >> $GITHUB_ENV 
          echo "ANSWER_BODY=${{ github.event.answer.body }}" >> $GITHUB_ENV
          echo "ANSWER_USER_NAME=${{ github.event.answer.user.login }}" >> $GITHUB_ENV
      
      - name: Set ChannelId(If answerd)
        if: env.ACTION == 'answered'
        run: |
          config=${{ fromJson($CONFIG) }}
          echo config
      - name: Set ChannelId(Not answerd)
        if: env.ACTION != 'answered'
        run: |
          echo "CHANNELID=${{ $CHANNELS['instructorChannelId'] }}
      
      - name: output
        run: |
          echo $ACTION
          echo $CHANNELID

