name: DiscussionNotification(created)

on:
  discussion:
    types: [created]

jobs:
  discussion:
    if: github.event.discussion.category.name == 'Q&A'
    runs-on: ubuntu-22.04
    steps:
      - name: Read config.json
        id: config
        uses: jaywcjlove/github-action-read-file@main
        with:
          path: config.json
      
      - name: Set ChannelId
        run: |
          echo "CHANNELID=${{ fromJson(steps.config.outputs.content)['instructorChannelId'] }}" >> $GITHUB_ENV
      
      - name: Send GitHub Action trigger data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.16.0
        with:
          channel-id: "${{ env.CHANNELID }}"
          payload: |
            "${{ "{
              "attachments": [
                {
                  "mrkdwn_in": ["text"],
                  "color": "#f1c40f",
                  "pretext": "<@U04TBP40V62><@U04TJEBURV0><@U054EJH9Y85>\n:rocket: *新しい質問が投稿されました* :rocket:",
                  "title": "${{ env.DISCUSSION_TITLE }}",
                  "title_link": "${{ env.DISCUSSION_URL }}",
                  "text": "${{　 env.DISCUSSION_BODY }}"
                }
              ]
            }" | jq }}"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          DISCUSSION_URL: ${{ github.event.discussion.html_url }}
          DISCUSSION_TITLE: ${{ github.event.discussion.title }}
          DISCUSSION_BODY: ${{ github.event.discussion.body }}
          DISCUSSION_USER_NAME: ${{ github.event.discussion.user.login }}
