name: DiscussionNotification

on:
  discussion:
    types: [created]

jobs:
  discussion:
    runs-on: ubuntu-22.04
    steps:
      - name: Read config.json
        id: config
        uses: jaywcjlove/github-action-read-file@main
        with:
          path: config.json
          
      - name: Get Discussion Action
        run: |
          echo "DISCUSSION_URL=${{ github.event.discussion.html_url }}" >> $GITHUB_ENV
          echo "DISCUSSION_TITLE=${{ github.event.discussion.title }}" >> $GITHUB_ENV
          echo "DISCUSSION_BODY=${{ github.event.discussion.body }}" >> $GITHUB_ENV
          echo "DISCUSSION_USER_NAME=${{ github.event.discussion.user.login }}" >> $GITHUB_ENV
      
      - name: Set ChannelId
        run: |
          echo "CHANNELID=${{ fromJson(steps.config.outputs.content)['instructorChannelId'] }}" >> $GITHUB_ENV
      
      - name: Send Message
        if: env.ACTION != 'answered'
        run: |
          pretext="<@U04TBP40V62><@U04TJEBURV0><@U054EJH9Y85>\n:rocket: *新しい質問が投稿されました* :rocket:"
          curl -H "Content-type: application/json" \
--data '{"channel":"C05243U3NAF","blocks":[{"type":"section","text":{"type":"mrkdwn","text":"Hi I am a bot that can post *_fancy_* messages to any public channel."}}]}' \
-H "Authorization: Bearer xoxb-4960072556352-5069366047717-lcNYdazgB1JMycO324x85zTL" \
-X POST https://slack.com/api/chat.postMessage
