name: DiscussionNotification(answered)

on:
  discussion:
    types: [answered]

jobs:
  discussion:
    if: github.event.discussion.category.name == 'Q&A'
    runs-on: ubuntu-22.04
    steps:
      - name: Read config.json
        id: config
        uses: jaywcjlove/github-action-read-file@main
        with:
          path: config.json
      
      - name: Set ChannelId
        run: |
          echo "CHANNELID=${{ fromJson(steps.config.outputs.content)['instructorChannelId'] }}" >> $GITHUB_ENV
      
      - name: Discussion Body
        id: discussion_body
        run: |
          discussion_body="${{ github.event.discussion.body }}"
          discussion_body="${discussion_body//$'\n'/\\n}"
          discussion_body="${discussion_body//$'\r'/\\r}" 
          echo $discussion_body
          echo "::set-output name=std_out::$discussion_body"
          
      - name: Answer Body
        id: answer_body
        run: |
          answer_body="${{ github.event.answer.body }}"
          answer_body="${answer_body//$'\n'/\\n}"
          answer_body="${answer_body//$'\r'/\\r}" 
          echo $discussion_body
          echo "::set-output name=std_out::$answer_body"
      
      - name: Send GitHub Action trigger data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.16.0
        with:
          channel-id: "${{ env.CHANNELID }}"
          payload: |
            {
              "attachments": [
                  {
                    "mrkdwn_in": ["text"],
                      "color": "#36a64f",
                      "pretext": "<!here>\n:tada: 質問が回答されました:tada: ",
                      "title": "${{ env.DISCUSSION_TITLE }}",
                      "title_link": "${{ env.DISCUSSION_URL }}",
                      "text": "${{ steps.discussion_body.outputs.std_out }}\n",
                      "fields": [
                        {
                            "title": "Answer",
                            "value": "${{ steps.answer_body.outputs.std_out }}",
                            "short": false
                        }
                      ]
                  }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          DISCUSSION_URL: ${{ github.event.discussion.html_url }}
          DISCUSSION_TITLE: ${{ github.event.discussion.title }}
          DISCUSSION_USER_NAME: ${{ github.event.discussion.user.login }}
