name: DiscussionNotification

on:
  discussion:
    types: [created, answered]

jobs:
  get_discussion_information:
    runs-on: ubuntu-22.04
    steps:
      - name: discussion
        run: |
          echo "ACTION=${{ github.event.action }}" >> $GITHUB_ENV
          echo "DISCUSSION_URL=${{ github.event.discussion.html_url }}" >> $GITHUB_ENV
          echo "DISCUSSION_TITLE=${{ github.event.discussion.title }}" >> $GITHUB_ENV
          echo "DISCUSSION_BODY=${{ github.event.discussion.body }}" >> $GITHUB_ENV
          echo "DISCUSSION_USER_NAME=${{ github.event.discussion.user.login }}" >> $GITHUB_ENV
      - name: answer
        if: env.ACTION == 'answered'
        run: |
          echo "ANSWER_ANSWER_URL=${{ github.event.answer.html_url }}" >> $GITHUB_ENV 
          echo "ANSWER_TITLE=${{ github.event.answer.title }}" >> $GITHUB_ENV
          echo "ANSWER_BODY=${{ github.event.answer.body }}" >> $GITHUB_ENV
          echo "ANSWER_USER_NAME=${{ github.event.answer.user.login }}" >> $GITHUB_ENV
  set_channel_id:
    runs-on: ubuntu-22.04
    steps:
      - name: load_json_file
        run: |
          channel_config=`cat ./config.json`
          channel_config="${channel_config//'%'/'%25'}"
          channel_config="${channel_config//$'\n'/'%0A'}"
          channel_config="${channel_config//$'\r'/'%0D'}"
          channel_config="${fromJson(channel_config)}
          echo "${{channel_config}}"
