name: CI

on:
  discussion:
    types: [created, answered]

jobs:
  discussion_created:
    runs-on: ubuntu-22.04
    steps:
      - name: get_discussion_info
        run: |
          echo "ACTION=${{ github.event.action }}" >> $GITHUB_ENV
          echo "DISCUSSION_URL=${{ github.event.discussion.html_url }}" >> $GITHUB_ENV
          echo "DISCUSSION_TITLE=${{ github.event.discussion.title }}" >> $GITHUB_ENV
          echo "DISCUSSION_BODY=${{ github.event.discussion.body }}" >> $GITHUB_ENV
          echo "DISCUSSION_USER_NAME=${{ github.event.discussion.user.login }}" >> $GITHUB_ENV
      - name: output
        run: |
          echo $ACTION
          echo $DISCUSSION_URL
          echo $DISCUSSION_TITLE
          echo $DISCUSSION_BODY
          echo $DISCUSSION_USER_NAME
