name: DiscussionNotification(comment)

on:
  discussion_comment:
    types: [created]

jobs:
  discussion:
    runs-on: ubuntu-22.04
    steps:
      - name: Read config.json
        id: config
        uses: jaywcjlove/github-action-read-file@main
        with:
          path: config.json

      - name: Get Discussion Action
        run: |
          echo "DISCUSSION_URL=${{ github.event.discussion.html_url }}" >> $GITHUB_ENV
          echo "DISCUSSION_TITLE=${{ github.event.discussion.title }}" >> $GITHUB_ENV
          echo "DISCUSSION_USER_NAME=${{ github.event.discussion.user.login }}" >> $GITHUB_ENV
          echo "COMMENT_BODY=${{ github.event.comment.body }}" >> $GITHUB_ENV
          echo "COMMENT_USER_NAME=${{ github.event.comment.user.login }}" >> $GITHUB_ENV
      
      - name: Set ChannelId & UserId（trainees）
        if: env.DISCUSSION_USER_NAME != 'ajj-k' && env.DISCUSSION_USER_NAME != 'tsuyuni'
        run: |
          echo "CHANNELID=${{ fromJson(steps.config.outputs.content)['trainees'][env.DISCUSSION_USER_NAME]['channelId'] }}" >> $GITHUB_ENV
          echo "USERID=${{ fromJson(steps.config.outputs.content)['trainees'][env.DISCUSSION_USER_NAME]['userId'] }}" >> $GITHUB_ENV
      
      - name: Send to Slack（trainees）
        id: slack_trainees
        if: env.COMMENT_USER_NAME != 'ajj-k' && env.COMMENT_USER_NAME != 'tsuyuni'
        uses: slackapi/slack-github-action@v1.16.0
        with:
          channel-id: "${{ env.CHANNELID }}"
          payload: |
            {
              "attachments": [
                  {
                    "mrkdwn_in": ["text"],
                      "color": "#f1c40f",
                      "pretext": "<@${{ env.USERID }}>\n:white_check_mark: *投稿に新しいコメントがつきました* :white_check_mark:",
                      "title": "${{ env.DISCUSSION_TITLE }}",
                      "title_link": "${{ env.DISCUSSION_URL }}",
                      "text": "${{ env.COMMENT_BODY }}"
                  }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
